package com.Authentication.AuthService.services.auth.wifakey;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.test.util.ReflectionTestUtils;

import java.io.File;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Cross-checks the migrated server-side LDPC decode against the Python
 * reference (WiFaKey_252's ONNX decoder pipeline that used to run inside the
 * client .exe). The fixture below — a random c' and its expected
 * SHA-256(reconstructed_key) — was generated by
 * WiFaKey_252/gen_decoder_fixture.py against the same neural_ms_decoder.onnx
 * now bundled at Authentication_Service/models/. A match here proves the
 * Java port (BPSK -> ONNX inference -> key extraction -> SHA-256) is
 * bit-identical to the logic that previously lived client-side.
 */
class LdpcDecoderServiceTest {

    private static final String C_PRIME_B64 =
            "AQABAAEBAAEBAQEBAAAAAAAAAQABAAEBAQEAAAABAQEBAQEAAQAAAAEAAQEBAAEBAAAAAQAAAQEAAQEBAQEAAQABAAEAAAEAAAEBAQAAAAAAAAABAQEBAAEBAQAAAAABAAEAAQAAAQEBAQAAAAEBAQAAAQEBAQEAAAAAAAAAAAAAAAEAAQABAQEBAAEBAAAAAAEBAQEBAQEAAQEAAAEBAQEAAAABAAABAAAAAQEAAQABAAAAAAEAAQABAAABAQEBAQABAQAAAAEAAQEBAQEBAAABAAAAAAAAAAAAAAABAAABAQEBAAEAAAABAAEBAAEBAQEAAQEBAQEAAAEAAQEBAQAAAAAAAAAAAAABAQEAAQAAAAEAAAEAAAEBAQEBAAEAAQABAAABAAAAAAEBAAEBAAABAQAAAQAAAQABAQABAAEAAQEBAAABAAABAAABAAABAQAAAQEBAAEAAQEAAQABAAAAAQEAAQABAAAAAAAAAAEAAAABAAEAAAAAAQEBAQEAAQEAAAAAAQEBAQABAQEBAAAAAAEAAAAAAAEAAQAAAQAAAQEBAAEAAQEBAQEAAQABAQEBAAEBAQEAAAEAAQEBAQABAAEAAQAAAAAAAQEAAQEBAAEAAAEBAAEBAQABAQAAAQEBAAEAAAEAAQEBAQEBAAEBAQEAAAEBAQAAAAABAQEBAAABAAEAAQAAAQEAAAEBAAAAAAAAAAEBAAABAAEBAAABAAEAAQEAAAEBAAEBAQAAAQEBAAABAAABAQAAAAEAAQAAAQEBAAEAAQEAAAABAAEAAAEBAQEAAQAAAQABAAAAAAEBAQEAAAEAAAAAAAABAAEAAAEBAQEAAQABAQEBAQEBAAEBAAABAAABAAABAAAAAAEAAQEAAQEAAAABAQEAAQABAAAAAQAAAAAAAAAAAAEAAQEBAQEBAAEAAQABAAABAAEBAAAAAAAAAQEAAAABAQAAAQABAQAAAAAAAAAAAQAAAQAAAAAAAQABAAABAQAAAQAAAAEAAAEAAAEAAAABAQAAAQABAQABAAEBAQAAAAAAAQABAQAAAAABAAEBAAEAAAEAAQEBAQABAQABAAABAQAAAAEAAAABAQEBAAEAAQ==";

    private static final String EXPECTED_HASH_B64 = "FjN5kDgpu8/Yx3O3RRGeRBuS4rfmexxklBMH9MwElP8=";

    private static LdpcDecoderService service;

    @BeforeAll
    static void setUp() throws Exception {
        File modelFile = new File("models/neural_ms_decoder.onnx");
        assumeTrue(modelFile.isFile(),
                "models/neural_ms_decoder.onnx not present — skipping decoder cross-check");

        service = new LdpcDecoderService(new DefaultResourceLoader());
        ReflectionTestUtils.setField(service, "decoderModelPath", "file:" + modelFile.getPath());
        ReflectionTestUtils.invokeMethod(service, "initialize");
    }

    @Test
    void reconstructKeyHash_matchesPythonReferenceFixture() {
        byte[] cPrime = Base64.getDecoder().decode(C_PRIME_B64);
        byte[] expected = Base64.getDecoder().decode(EXPECTED_HASH_B64);

        byte[] actual = service.reconstructKeyHash(cPrime);

        assertArrayEquals(expected, actual,
                "Java decode must reproduce the exact SHA-256 the Python ONNX pipeline produced for the same c'");
    }
}
