services:
  postgres:
    image: postgres:17
    container_name: postgres-authservice-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authservice-db
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis-authservice
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "redis123"
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-authservice
    ports:
      - "8001:5540"
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: