spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3306/AuthServiceDB
spring.datasource.username=root
spring.datasource.password=auth123

spring.jpa.hibernate.ddl-auto=none

spring.config.import=optional:file:.env[.properties]

logging.level.com.Authentication.AuthService=DEBUG

server.port=8080
server.url=${SERVER_URL:http://localhost:8080}
# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# JWT Configuration
jwt.secret=4fa3b190e8d42319b74e3d1ace09f85b1c9a4f02c3475debc7a92f38dc1d548e
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000
jwt.issuer=auth-service
